### ISSUE TITLE
Frequent Request Timeout

### ISSUE THREAD

**Issue by akshaybabloo** [Azure/azure-functions-core-tools#1342]
I have been getting frequent request timeouts when trying to publish an app

```
Response:
StatusCode: 408, ReasonPhrase: 'Request Timeout', Version: 1.1, Content: System.Net.Http.HttpConnection+HttpConnectionResponseContent, Headers:
{
  Cache-Control: no-cache
  Pragma: no-cache
  Strict-Transport-Security: max-age=31536000; includeSubDomains
  Server: Microsoft-IIS/10.0
  X-AspNet-Version: 4.0.30319
  X-Powered-By: ASP.NET
  x-ms-failure-cause: service
  x-ms-ratelimit-remaining-subscription-reads: 11998
  x-ms-request-id: 6b191f14-bf79-427a-8f78-fee6730f07ac
  x-ms-correlation-request-id: 6b191f14-bf79-427a-8f78-fee6730f07ac
  x-ms-routing-request-id: AUSTRALIAEAST:20190525T103555Z:6b191f14-bf79-427a-8f78-fee6730f07ac
  X-Content-Type-Options: nosniff
  Date: Sat, 25 May 2019 10:35:55 GMT
  Connection: close
  Content-Length: 618
  Content-Type: application/json; charset=utf-8
  Expires: -1
}
{"Code":"RequestTimeout","Message":"The operation timed out and could not be completed. Please retry the action or try again later.","Target":null,"Details":[{"Message":"The operation timed out and could not be completed. Please retry the action or try again later."},{"Code":"RequestTimeout"},{"ErrorEntity":{"ExtendedCode":"51007","MessageTemplate":"The operation timed out and could not be completed. Please retry the action or try again later.","Parameters":[],"Code":"RequestTimeout","Message":"The operation timed out and could not be completed. Please retry the action or try again later."}}],"Innererror":null}
```

**Update**

And now I am getting this error:

```
Response:
StatusCode: 401, ReasonPhrase: 'Unauthorized', Version: 1.1, Content: System.Net.Http.HttpConnection+HttpConnectionResponseContent, Headers:
{
  Cache-Control: no-cache
  Pragma: no-cache
  WWW-Authenticate: Bearer authorization_uri="https://login.windows.net/5e022ca1-5c04-4f87-8db7-d588726274e3", error="invalid_token", error_description="The access token has expired."
  x-ms-failure-cause: gateway
  x-ms-request-id: bce08ada-c0cd-469e-98b8-0c737ea55f25
  x-ms-correlation-request-id: bce08ada-c0cd-469e-98b8-0c737ea55f25
  x-ms-routing-request-id: AUSTRALIAEAST:20190526T070502Z:bce08ada-c0cd-469e-98b8-0c737ea55f25
  Strict-Transport-Security: max-age=31536000; includeSubDomains
  X-Content-Type-Options: nosniff
  Date: Sun, 26 May 2019 07:05:02 GMT
  Connection: close
  Content-Type: application/json; charset=utf-8
  Expires: -1
  Content-Length: 172
}
{"error":{"code":"ExpiredAuthenticationToken","message":"The access token expiry UTC time '5/26/2019 7:04:42 AM' is earlier than current UTC time '5/26/2019 7:05:02 AM'."}}


Azure.Functions.Cli.Common.CliException: Error calling sync triggers (Unauthorized).
   at Azure.Functions.Cli.Helpers.RetryHelper.Retry(Func`1 func, Int32 retryCount, TimeSpan retryDelay, Boolean displayError) in C:\azure-functions-cli\src\Azure.Functions.Cli\Helpers\RetryHelper.cs:line 29
   at Azure.Functions.Cli.Actions.AzureActions.PublishFunctionAppAction.SyncTriggers(Site functionApp) in C:\azure-functions-cli\src\Azure.Functions.Cli\Actions\AzureActions\PublishFunctionAppAction.cs:line 336
   at Azure.Functions.Cli.Actions.AzureActions.PublishFunctionAppAction.PublishFunctionApp(Site functionApp, GitIgnoreParser ignoreParser, IDictionary`2 additionalAppSettings) in C:\azure-functions-cli\src\Azure.Functions.Cli\Actions\AzureActions\PublishFunctionAppAction.cs:line 323
   at Azure.Functions.Cli.Actions.AzureActions.PublishFunctionAppAction.RunAsync() in C:\azure-functions-cli\src\Azure.Functions.Cli\Actions\AzureActions\PublishFunctionAppAction.cs:line 166
   at Azure.Functions.Cli.ConsoleApp.RunAsync[T](String[] args, IContainer container) in C:\azure-functions-cli\src\Azure.Functions.Cli\ConsoleApp.cs:line 55
```

I have logged out Azure CLI and logged back in, but still the same problem.

**Update 2**

This is happening on macos, for Windows see #1339
