### ISSUE TITLE
Running behind ingress

### ISSUE THREAD

**Issue by 00vareladavid** [Azure/azure-functions-core-tools#1879]
I am trying to deploy azure functions to AKS. Using a LoadBalancer as the service type works great. But I am having issues using ClusterIP as the service.

This is what I run:
```
func kubernetes deploy \                                                                                                       
        --name graphql \                                                                                                       
        --namespace graphql \                                                                                                  
        --registry xxx.azurecr.io \                                                                                        
        --service-type ClusterIP                                                                                               
```

And my ingress looks like this:
```
apiVersion: extensions/v1beta1                                                                                                 
kind: Ingress                                                                                                                  
metadata:                                                                                                                      
  annotations:                                                                                                                 
    kubernetes.io/ingress.class: nginx                                                                                         
  name: graphql                                                                                                                
  namespace: graphql                                                                                                           
spec:                                                                                                                          
  rules:                                                                                                                       
    - host: foo.com                                                                                                   
      http:                                                                                                                    
        paths:                                                                                                                 
          - path: /graphql                                                                                                     
            backend:                                                                                                           
              serviceName: graphql-http                                                                                        
              servicePort: 80                                                                                                  
  tls:                                                                                                                         
      - hosts:                                                                                                                 
          - foo.com                                                                                                   
        secretName: aks-ingress-tls                                                                                            
   ```

I already have annotated the service according to [this issue](https://github.com/Azure/azure-functions-core-tools/issues/1310). Is anything else I need to do to set up azure functions with a custom ingress? Thanks for your time
