### ISSUE TITLE
No scaler found for TimerTriggers in Kubernetes ScaledObjects

### ISSUE THREAD

**Issue by CarlosLanderas** [Azure/azure-functions-core-tools#1926]
Hello, I am trying to deploy to kubernetes an Azure Functions v3 project that has several Http Functions and one TimeTrigger function, and I see the created scaled object is the one below after executing the following command:

func kubernetes deploy --name timered --registry localhost:5000 --namespace 

The default configured replicas are zero

```yaml
    uid: a8cdf04d-178f-4cdd-8add-aa455219cf28
  spec:
    maxReplicaCount: 5
    minReplicaCount: 1
    pollingInterval: 5
    scaleTargetRef:
      deploymentName: timered
    triggers:
    - metadata:
        name: myTimer
        schedule: '*/5 * * * * *'
        type: timerTrigger
      type: timertrigger
kind: List
```

I do not know what is the purpose of creating a trigger with type "timertrigger", as It seems it does not exist in keda, or maybe I am missing some pieces.

"Reconciler error","controller":"scaledobject-controller","request":"delete/timered","error":"error getting scaler for trigger #0: no scaler found for type: timertrigger"

Are timertriggers thought to be working with ScaledObjects?

Thanks
