### ISSUE TITLE
Python remote build with private PyPi package on Azure DevOps Artifacts

### ISSUE THREAD

**Issue by thiezn** [Azure/azure-functions-core-tools#2277]
Hi,

I'm trying to deploy a python Azure Function app using remote build using a Python package hosted on Azure DevOps Artifacts. I'm using the PipAuthenticate task to authenticate against Azure Artifacts PyPi feed. I've also added the PIP_EXTRA_INDEX_URL to my function app pointing to the Azure Artifacts feed.

Here's the Azure Pipeline yaml file I'm using to deploy the app.

```yaml
      - task: PipAuthenticate@1
        inputs:
          artifactFeeds: <...removed...>

      # Install azure function app using remote build.
      # NOTE you need to add a application/env variable to your function app for installing Az Artificacts PyPi
      # packages:
      #     "name": "PIP_EXTRA_INDEX_URL",
      #     "value": "https://<...removed...>.pkgs.visualstudio.com/<...removed...>/_packaging/<...removed...>/pypi/simple"
      - task: AzureCLI@2
        displayName: Publish function app
        inputs:
          azureSubscription: $(serviceConnectionToAzure)
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: |
            func azure functionapp publish $(appName) --python --build remote
```

The azure function remote build starts but when trying to install its dependencies it hangs for a long time and eventually fails with a 404 error message. I suspect the remote build is not picking up on the credentials generated by the PipAuthenticate task.

Is there a way to add a (pip configuration) file or update an environment variable on the remote build environment? This way I could pass on the credentials generated by PipAuthenticate to the ```func azure functionapp publish``` command and (hopefully) get the remote build to work.

```
Getting site publishing info...
Creating archive for current directory...
Performing remote build for functions project.
Deleting the old .python_packages directory
> /usr/local/Cellar/azure-functions-core-tools@3/3.0.2245/gozip -base-dir <...removed local dir...>-input-file /var/folders/lz/wd_xkfj9171fy0280pxgrfhm0000gn/T/tmpka63yS.tmp -output /var/folders/lz/wd_xkfj9171fy0280pxgrfhm0000gn/T/tmpkqrgxf.tmp
Uploading 27.12 KB [##############################################################################]
Remote build in progress, please wait...
Updating submodules.
Preparing deployment for commit id '4f81804cb5'.
Repository path is /tmp/zipdeploy/extracted
Running oryx build...
Command: oryx build /tmp/zipdeploy/extracted -o /home/site/wwwroot --platform python --platform-version 3.8 -p packagedir=.python_packages/lib/site-packages
Operation performed by Microsoft Oryx, https://github.com/Microsoft/Oryx
You can report issues at https://github.com/Microsoft/Oryx/issues

Oryx Version: 0.2.20200929.1, Commit: 0266eb9f094e3f18e2d73c438dcbb2be70841922, ReleaseTagName: 20200929.1

Build Operation ID: |YvYIQVOy29g=.9b8143d5_
Repository Commit : 4f81804cb5624b1d900cca171d41b9e5

Detecting platforms...
Detected following platforms:
  python: 3.8.6
Version '3.8.6' of platform 'python' is not installed. Generating script to install it...


Source directory     : /tmp/zipdeploy/extracted
Destination directory: /home/site/wwwroot


Downloading and extracting 'python' version '3.8.6' to '/tmp/oryx/platforms/python/3.8.6'...
Downloaded in 2 sec(s).
Verifying checksum...
Extracting contents...
Done in 16 sec(s).

Python Version: /tmp/oryx/platforms/python/3.8.6/bin/python3.8

[16:28:57+0000] Looking in indexes: https://pypi.org/simple, https://<...removed...>.pkgs.visualstudio.com/<...removed...>/_packaging/<...removed...>/pypi/simple
System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
   at Azure.Functions.Cli.Helpers.RetryHelper.Retry(Func`1 func, Int32 retryCount, TimeSpan retryDelay, Boolean displayError) in D:\a\1\s\src\Azure.Functions.Cli\Helpers\RetryHelper.cs:line 29
   at Azure.Functions.Cli.Helpers.KuduLiteDeploymentHelpers.InvokeRequest[T](HttpClient client, HttpMethod method, String url) in D:\a\1\s\src\Azure.Functions.Cli\Helpers\KuduLiteDeploymentHelpers.cs:line 153
   at Azure.Functions.Cli.Helpers.KuduLiteDeploymentHelpers.GetDeploymentStatusById(HttpClient client, Site functionApp, String id) in D:\a\1\s\src\Azure.Functions.Cli\Helpers\KuduLiteDeploymentHelpers.cs:line 99
   at Azure.Functions.Cli.Helpers.KuduLiteDeploymentHelpers.WaitForConsumptionServerSideBuild(HttpClient client, Site functionApp, String accessToken, String managementUrl) in D:\a\1\s\src\Azure.Functions.Cli\Helpers\KuduLiteDeploymentHelpers.cs:line 35
   at Azure.Functions.Cli.Actions.AzureActions.PublishFunctionAppAction.PerformServerSideBuild(Site functionApp, Func`1 zipFileFactory, Func`2 deploymentStatusPollTask) in D:\a\1\s\src\Azure.Functions.Cli\Actions\AzureActions\PublishFunctionAppAction.cs:line 718
   at Azure.Functions.Cli.Actions.AzureActions.PublishFunctionAppAction.HandleLinuxConsumptionPublish(Site functionApp, Func`1 zipFileFactory) in D:\a\1\s\src\Azure.Functions.Cli\Actions\AzureActions\PublishFunctionAppAction.cs:line 460
   at Azure.Functions.Cli.Actions.AzureActions.PublishFunctionAppAction.PublishFunctionApp(Site functionApp, GitIgnoreParser ignoreParser, IDictionary`2 additionalAppSettings) in D:\a\1\s\src\Azure.Functions.Cli\Actions\AzureActions\PublishFunctionAppAction.cs:line 303
   at Azure.Functions.Cli.Actions.AzureActions.PublishFunctionAppAction.RunAsync() in D:\a\1\s\src\Azure.Functions.Cli\Actions\AzureActions\PublishFunctionAppAction.cs:line 173
   at Azure.Functions.Cli.ConsoleApp.RunAsync[T](String[] args, IContainer container) in D:\a\1\s\src\Azure.Functions.Cli\ConsoleApp.cs:line 66
```

Cheers,
Thiezn

**Comment by thiezn** [comment]
Actually, minutes after writing this issue I figured out a way to tackle this myself!

The PipAuthenticate task exports the environmental variable PIP_EXTRA_INDEX_URL that includes the credentials. I added an additional step to update the Azure Function App application setting using the ``` az functionapp config appsettings set``` command, after which the remote build succeeded.

Here's my pipeline for others to use if needed.

```yaml
      - task: PipAuthenticate@1
        inputs:
          artifactFeeds:  <...removed...>

      # Install azure function app using remote build.
      - task: AzureCLI@2
        displayName: Publish function app
        inputs:
          azureSubscription: $(serviceConnectionToAzure)
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: |
            # Overwrite the PIP Environment variable with Pip credentials for Azure DevOps Artifacts feed and then publish function app
            az functionapp config appsettings set --name $(appName) --resource-group $(rgName) --settings 
            func azure functionapp publish $(appName) --python --build remote
```
