### ISSUE TITLE
func kubernetes deploy, error on keda using storage account blob action

### ISSUE THREAD

**Issue by felpasl** [Azure/azure-functions-core-tools#2435]
I got this error on keda 2.x "error getting scaler for trigger #0: error parsing azure blob metadata: no blobContainerName given"

I managed to solve exporting a file from --dry-run and put the value of metadata blobContainerName and worked. Maybe do this automaticaly are better because to solve I spend some time on this message "Failed to ensure HPA is correctly created for ScaledObject" on ScaledObject without any tips.

**Comment by apawast** [comment]
@felpasl  could you please share more specifics in the change you made so we can determine if it's possible to do this automatically?

**Comment by felpasl** [comment]
sry on yaml generated by func is that
```
  triggers:
  - type: azure-blob
    metadata:
      path: blobContainerName/{name}
      connectionFromEnv: blobConnName
```

and i got an error, solving with this change:

```
  triggers:
  - type: azure-blob
    metadata:
      path: blobContainerName/{name}
      connectionFromEnv: blobConnName
      blobContainerName: blobContainerName
```
