### ISSUE TITLE
Missing storageConnectionFromEnv with KEDA EventHubs scaler

### ISSUE THREAD

**Issue by TsuyoshiUshio** [Azure/azure-functions-core-tools#2505]
For the usage of KEDA, I found the `storageConnectionFromEnv` is missing when I create this local.settings.json

```json
{
  "IsEncrypted": false,
  "Values": {
    "FUNCTIONS_WORKER_RUNTIME": "node",
    "AzureWebJobsStorage": "<<MY_STORAGE>>",
    "Connection": "<<CONNECTION>>",
    "EventHubConnection": "<<CONNECTION>>",
    "APPINSIGHTS_INSTRUMENTATIONKEY":"<<MY_INSTRUMENTATION_KEY>>",
    "APPLICATIONINSIGHTS_CONNECTION_STRING":"<<CONNECTION_STRING>>"
  }
}
```

I found the scaled object has this metadata, that is `storageConnectionFromEnv` missing. https://keda.sh/docs/2.2/scalers/azure-event-hub/

```
  - metadata:
      cardinality: many
      connectionFromEnv: EventHubConnection
      consumerGroup: $Default
      dataType: string
      direction: in
      eventHubName: workitems
    type: azure-eventhub
```
