### ISSUE TITLE
Kubernetes deploy: Add resource requests/limits for function app containers

### ISSUE THREAD

**Issue by cgillum** [Azure/azure-functions-core-tools#2509]
Relevant K8s documentation: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/

Let's add k8s resource demands to the containers yaml we generate for function apps. For example, we might require that each function app container is guaranteed 512 MiB RAM and 0.5 CPUs, based on what we know about Functions host requirements.

```yml
  containers:
  - name: my-function-app
    image: myrepo/my-function-app:latest
    resources:
      - requests:
          memory: "512Mi"
          cpu: "500m"
```

Ideally customers could participate in configuring this via command-line arguments, but we should also have reasonable defaults based on what we know the needs of our own runtimes. This will be important to help ensure a reliable runtime experience.

**Context:**
I was running some simple scale tests and ran into some interesting issues.

* Using KEDA to scale-out my app, I quickly (and accidentally) scaled out my function app to 100 instances on a 2 VM cluster. This quickly brought down my whole cluster.
* Even after reducing my scale-out to just 5 instances, I ran into some severe reliability issues that appear to be performance related.

Having resource requests configured for my app would have been very helpful to mitigate these issues.
