### ISSUE TITLE
func kubernetes deploy is only creating a secret

### ISSUE THREAD

**Issue by amcorch** [Azure/azure-functions-core-tools#2633]
Hello, I am following the steps outlined in the [documentation](https://github.com/Azure/azure-functions-core-tools#getting-started-on-kubernetes), however when I run the following command
`func kubernetes deploy --name dockerfunctiontest --registry *** --dry-run`

I am receiving this output:
```
data:
  AzureWebJobsStorage: VXNlRGV2ZWxvcG1lbnRTdG9yYWdlPXRydWU=
  FUNCTIONS_WORKER_RUNTIME: ZG90bmV0LWlzb2xhdGVk
apiVersion: v1
kind: Secret
metadata:
  name: dockerfunctiontest
---
```

I can confirm that there is an image in my container repository named dockerfunctiontest and it is tagged with latest.

If I run the command without the --dry-run argument, the secret is created in my aks cluster.

Is there anything I might be missing so that the deployment/scaledobject are also created on my aks cluster?
