### ISSUE TITLE
Your Azure Function App has 'FUNCTIONS_WORKER_RUNTIME' set to 'dotnetIsolated' while your local project is set to 'dotnet'.

### ISSUE THREAD

**Issue by Planche95** [Azure/azure-functions-core-tools#3051]
Hi I'm having trouble with azure function version ~4, with dotnetisolated.

Im using gitlab pipeline with script:

```
image: mcr.microsoft.com/dotnet/sdk:6.0

.install_dependencies: &install_dependencies
  - curl -sL https://aka.ms/InstallAzureCLIDeb | bash
  - apt-get install curl && curl -sL https://deb.nodesource.com/setup_12.x | bash -
  - apt-get install nodejs
  - npm install -g azure-functions-core-tools@4 --unsafe-perm true

deploy dev:
  stage: deploy
  script:
    - *project_dir
    - *install_dependencies
    - az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID
    - func azure functionapp publish $AZURE_FUNCTION_NAME --csharp
```

my function app configs:

![image](https://user-images.githubusercontent.com/18653765/167589676-925a74d2-ce55-4203-aabe-8ebef187bd34.png)

I tried solution from here: https://github.com/Azure/azure-functions-core-tools/issues/2524

But it doesn't work for me, I also tried running commands from the output directory, and if local.settings.json is present there:
![image](https://user-images.githubusercontent.com/18653765/167590375-3ccf07d6-f6a3-4460-9c35-40c78d53de09.png)

any ideas?
