### ISSUE TITLE
func kubernetes deploy should not overwrite spec.containers.envfrom

### ISSUE THREAD

**Issue by vigouredelaruse** [Azure/azure-functions-core-tools#3284]
func kubernetes deploy overwrites the spec.containers.envfrom path and does not provide a way to supply references to existing secrets or configmaps as per the visual exhibit

```

    spec:
      containers:
        - name: somefunc-http
          image: docker.io/repo/image:latest
          ports:
            - containerPort: 80
              protocol: TCP
          envFrom:
            - secretRef:
                name: somefunc
            - configMapRef:
                name: no_way_to_supply_as_option_and_overwritten_on_subsequent_deploy
          env:

```

instead, func kubernetes deploiy should 
* patch spec.containers.envFrom 
* permit additional envFrom references to be supplied during deployment

currently [this ](https://github.com/Azure/azure-functions-core-tools/blob/v4.x/src/Azure.Functions.Cli/Kubernetes/KubernetesHelpers.cs)seems to be the the applicable code

this code is annotated with some triage 
```
            int resourceIndex = 0;
            if (useConfigMap)
            {
                var configMap = GetConfigMap(name, @namespace, secrets);
                result.Insert(resourceIndex, configMap);
                resourceIndex++;
                foreach (var deployment in deployments)
                {
                   #region will need
                   // will need different code paths for patch vs put
                   // will need to read the existing deployment and get array of current envFrom
                    var svc = await KubectlHelper.KubectlGet<JObject>($"{deployment.Metadata.Name}-deployment --namespace {deployment.Metadata.Namespace}");
                   // will need to diff the existing envFrom with what's about to be rendered

                    var endpoint = svc.SelectToken("spec.template.spec.containers.envFrom ")?.ToString();
                  #endregion will need 

                    // looks like there's a need for an inner loop or some clever linq set operation here that iterates the array of existing envfrom
                   // minus the below keys being rendered - patch vs put
                    deployment.Spec.Template.Spec.Containers.First().EnvFrom = new ContainerEnvironmentFromV1[]
                    {
                        new ContainerEnvironmentFromV1
                        {
                            ConfigMapRef = new NamedObjectV1
                            {
                                Name = configMap.Metadata.Name
                            }
                        }
                    };
                }
            }
```
the current workflow is hampered by the need to patch this field after each redeployment
regards
