### ISSUE TITLE
az functionapp show consistently fails the first time

### ISSUE THREAD

**Issue by jackawatts** [Azure/azure-functions-core-tools#3331]
As per the title.

Specifically:
Running a yaml pipeline in Azure Devops

modified example below.

```yaml
            - task: AzureCLI@2
              displayName: 'Get function urls and keys'
              inputs:
                azureSubscription: 'xyz'
                scriptType: 'pscore'
                scriptLocation: 'inlineScript'
                inlineScript: |
                  Write-Host "rgName: $(rgName)"
                  Write-Host "functionAppName: $(functionAppName)"
                  $statusUrl = az functionapp function show --resource-group $(rgName) --name $(functionAppName) --function-name 'status' --query 'invokeUrlTemplate'
                  Write-Host "##vso[task.setvariable variable=statusUrl]$($statusUrl.Trim('"'))"
```

Specifically any such code like the above always fails the first time after the referenced function is deployed.  It seems to work reliably and successfully every other time after.

Do I need to write a sleep loop to address this? :(

**Actual Result**
```
ERROR: (NotFound) Error retrieving function.
Code: NotFound
Message: Error retrieving function.
You cannot call a method on a null-valued expression.
At /home/vsts/work/_temp/azureclitaskscript1681431997529_inlinescript.ps1:8 char:57
+                                                  ~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (:) [], ParentContainsErrorRecordException
+ FullyQualifiedErrorId : InvokeMethodOnNull
##[error]Script failed with exit code: 1
````

**Expected result:**
$statusUrl has a non-null value and the script executes as expected.
