### ISSUE TITLE
Uncaught exception with latest version crashes container

### ISSUE THREAD

**Issue by somesylvie** [Azure/azure-functions-core-tools#4158]
### Version

4.0.6543 and 4.0.6594 (even though 6543 is the 'latest' on the NPM website, when we run `npm install -g azure-functions-core-tools` without specifying a version, we end up with the unlisted 6594)

### Description

When running an azure function docker container, we recently started to see this error, which then crashes the container: `terminate called after throwing an instance of 'PAL_SEHException'`
Nothing in the Azure function or its configuration has changed recently. When we explicitly specify an older version of the core tools (such as `4.0.6280`), we don't have any issues

### Steps to reproduce

Run the azure function via docker compose: https://github.com/CDCgov/reportstream-sftp-ingestion/blob/main/docker-compose.yml#L65
Note that the installed version of core tools is the unlisted 6594, though we see the `PAL_SEHException` with version 6543 as well
We do not get the error if we change [line 76](https://github.com/CDCgov/reportstream-sftp-ingestion/blob/main/docker-compose.yml#L76) to `npm install -g azure-functions-core-tools@4.0.6280`
This is happening for at least 3 engineers on my team, all on Mac (either M1 or M3)

**Comment by liliankasem** [comment]
Thanks for reporting the issue. I am able to repro and see the same problem reported (running on a Mac (M3)), and we were not able to repro on Windows so it does seem to be an amd64 related issue.

Interestingly, the last run I did threw a new exception:

`The type initializer for 'Microsoft.Extensions.DependencyInjection.DependencyInjectionEventSource' threw an exception.`

Versions `4.0.6543` and `4.0.6594` of the core tools both use the new out-of-proc host so there could be many things that started causing this problem. I will continue to investigate and let you know if any progress is made.

**Comment by liliankasem** [comment]
@somesylvie question about your scenario. Why are you installing core tools in the container? I was looking at the code you shared:

https://github.com/CDCgov/reportstream-sftp-ingestion/blob/689c937b4b24c26a4941e3b9566cd5e29b3cf33f/docker-compose.yml#L65

And you should be able to run the application just fine without `command` since the image will start your application e.g:

```yml
  azure-function:
    image: mcr.microsoft.com/azure-functions/node:4-node20
    volumes:
      - ./azure_functions:/home/site/wwwroot
    ports:
      - "7072:7071"
    environment:
      AzureWebJobsScriptRoot: /home/site/wwwroot
      AzureFunctionsJobHost__Logging__Console__IsEnabled: true
      AzureWebJobs.HttpExample.Disabled: "true"
      AzureWebJobsStorage: DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://sftp-Azurite:10000/devstoreaccount1;QueueEndpoint=http://sftp-Azurite:10001/devstoreaccount1;TableEndpoint=http://sftp-Azurite:10002/devstoreaccount1; # pragma: allowlist secret
      AZURE_STORAGE_CONNECTION_STRING: DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://sftp-Azurite:10000/devstoreaccount1;QueueEndpoint=http://sftp-Azurite:10001/devstoreaccount1; # pragma: allowlist secret
    networks:
      - sftp
    depends_on:
      azure-cli:
        condition: service_completed_successfully
      sftp-server:
        condition: service_started
```
