### ISSUE TITLE
Kubernetes integration with AppSettings

### ISSUE THREAD

**Issue by TsuyoshiUshio** [Azure/azure-functions-core-tools#625]
Hi I tried Kubernetes integration feature. It is fantastic. I have some feedback by my experience to play with Queue trigger of node.js. 

# AppSettings configration

There is no way to configure AppSettings.  Do we have any measure to configure this? For example, for the queue trigger, we need to configure StorageAccount connection strings. 

Personally, I've export the yaml file, then edit the yaml file with environment variables. 

```bash
kubectl get deployments queuefunction-deployment -o yaml --namespace azure-functions > deployment.yaml
```

_deployment.yaml_ 

```
:
    spec:
      containers:
        - image: tsuyoshiushio/queuefunction-azurefunc
          imagePullPolicy: Always
          name: queuefunction-deployment
          env:
            - name: AzureWebJobsStorage
              value: YOUR_STORAGE_ACCOUNT_CONNECTION_STRING_HERE
          ports:
            - containerPort: 80
          protocol: TCP
:
```

I recommend your tool automatically to do it from some config files.  In here 

https://github.com/Azure/azure-functions-core-tools/blob/master/src/Azure.Functions.Cli/Actions/DeployActions/Platforms/KubernetesPlatform.cs#L155

Or better way is use ConfigMap or Secret of Kubernetes.  :) 

* [Define Environment Variables for a Container](https://kubernetes.io/docs/tasks/inject-data-application/define-environment-variable-container/)
* [Configure a Pod to Use a ConfigMap](https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/)
* [Secrets](https://kubernetes.io/docs/concepts/configuration/secret/)

 # yaml (or json) file export feature

According your code, you always delete the temporary deployment.json file. 

https://github.com/Azure/azure-functions-core-tools/blob/master/src/Azure.Functions.Cli/Actions/DeployActions/Platforms/KubernetesPlatform.cs#L101

However, a lot of k8s folks uses helm or yaml for the deployment.  We can export it manually, however, if your tool have an option to leave the yaml file, people might like it. 

# LoadBalancer

We don't need LoadBalancer when we don't need external IP address like Queue Trigger. :) 

https://github.com/Azure/azure-functions-core-tools/blob/master/src/Azure.Functions.Cli/Actions/DeployActions/Platforms/KubernetesPlatform.cs#L150

These are my feedback. Thank you for the great feature! I'm really excited about this! 

FYI: I wrote a blog about this topic. 

https://medium.com/@tsuyoshiushio/playing-with-azure-functions-kubernetes-integration-9048908bfc2a
